// prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

#[cfg(target_os = "windows")]
use std::os::windows::process::CommandExt;

use std::process::Command;
use std::str::FromStr;

#[macro_use]
mod errors;
use errors::{DescriptorType, TempuraError, TempuraErrorType};
mod network;
use network::{HwiNetwork, Network};

// tauri and other framework imports
use serde::{Deserialize, Serialize};
use specta::Type;
use specta_typescript::Typescript;

// bdk and bitcoin imports
use bdk;
use bdk::bitcoin::secp256k1::Secp256k1;
use bdk::blockchain::ElectrumBlockchain;
use bdk::database::MemoryDatabase;
use bdk::descriptor::IntoWalletDescriptor;
use bdk::electrum_client::Client;
use bdk::SyncOptions;

/**
 * types
 */

#[derive(Default, Serialize, Deserialize, Type)]
pub struct AddressInfo {
  pub index: u32,
  pub address: String,
}

impl From<bdk::wallet::AddressInfo> for AddressInfo {
  fn from(addrinfo: bdk::wallet::AddressInfo) -> Self {
    Self {
      index: addrinfo.index,
      address: addrinfo.address.to_string(),
    }
  }
}

// this type is copied from BDK so that we can specta-derive it,
// but unfortunately u64 is not supported, so we must convert to string.
#[derive(Default, Serialize, Deserialize, Type)]
struct Balance {
  /// All coinbase outputs not yet matured
  pub immature: String,
  /// Unconfirmed UTXOs generated by a wallet tx
  pub trusted_pending: String,
  /// Unconfirmed UTXOs received from an external wallet
  pub untrusted_pending: String,
  /// Confirmed and immediately spendable balance
  pub confirmed: String,
}

impl From<bdk::Balance> for Balance {
  fn from(balance: bdk::Balance) -> Self {
    Balance {
      immature: balance.immature.to_string(),
      trusted_pending: balance.trusted_pending.to_string(),
      untrusted_pending: balance.untrusted_pending.to_string(),
      confirmed: balance.confirmed.to_string(),
    }
  }
}

// again, unfortunately u64 is not supported, so we must convert to string for number values.
#[derive(Default, Serialize, Deserialize, Type)]
pub struct PsbtDetails {
  pub psbt: String,
  pub txid: String,
  pub received: String,
  pub sent: String,
  pub fee: Option<String>,
}

impl PsbtDetails {
  pub fn new(psbt: String, details: bdk::TransactionDetails) -> Self {
    PsbtDetails {
      psbt: psbt,
      txid: details.txid.to_string(),
      received: details.received.to_string(),
      sent: details.sent.to_string(),
      fee: match details.fee {
        None => None,
        Some(fee) => Some(fee.to_string()),
      },
    }
  }
}

/**
 * utilities
 */

fn get_blockchain(
  network: Network,
  electrum: Option<String>,
) -> Result<ElectrumBlockchain, TempuraError> {
  let connection = match electrum {
    Some(electrum) => electrum,
    None => match network {
      Network::Testnet => "electrum.blockstream.info:60001".to_string(),
      Network::Bitcoin => "blockstream.info:110".to_string(),
      Network::Regtest => "localhost:50021".to_string(),
      _ => {
        return Err(TempuraError::new(
          TempuraErrorType::NetworkError,
          "You must specify an electrum server for this network",
        ))
      }
    },
  };

  let client = resolve!(Client::new(&connection), TempuraErrorType::ClientError);
  Ok(ElectrumBlockchain::from(client))
}

fn get_hwi() -> Result<Command, TempuraError> {
  let hwi_path = find_hwi()?;

  #[allow(unused_mut)]
  let mut command = Command::new(hwi_path);
  #[cfg(target_os = "windows")]
  {
    const COMMAND_FLAG_CREATE_NO_WINDOW: u32 = 0x08000000;
    command.creation_flags(COMMAND_FLAG_CREATE_NO_WINDOW);
  }
  Ok(command)
}

fn get_wallet(
  network: Network,
  receive: String,
  change: Option<String>,
) -> Result<bdk::Wallet<MemoryDatabase>, TempuraError> {
  let secp = Secp256k1::new();
  let network: bdk::bitcoin::Network = network.into();
  let receive = resolve!(
    receive.into_wallet_descriptor(&secp, network),
    TempuraErrorType::DescriptorError(DescriptorType::Receive)
  );
  let change = match change {
    Some(change) => Some(resolve!(
      change.into_wallet_descriptor(&secp, network),
      TempuraErrorType::DescriptorError(DescriptorType::Change)
    )),
    None => None,
  };

  Ok(resolve!(
    bdk::Wallet::new(
      receive,
      change,
      network,
      bdk::database::MemoryDatabase::default()
    ),
    TempuraErrorType::ClientError
  ))
}

/**
 * interface functions
 */

#[tauri::command]
#[specta::specta]
async fn address(
  network: String,
  descriptor: String,
  electrum: Option<String>,
) -> Result<AddressInfo, TempuraError> {
  let network = Network::from_str(&network)?;
  let blockchain = get_blockchain(network, electrum)?;
  let wallet = get_wallet(network, descriptor, None)?;

  // Execute blocking wallet sync and balance retrieval in a separate thread context.
  tokio::task::block_in_place(|| {
    resolve!(
      wallet.sync(&blockchain, SyncOptions::default()),
      TempuraErrorType::WalletSyncError
    );

    let addr = resolve!(
      wallet.get_address(bdk::wallet::AddressIndex::LastUnused),
      TempuraErrorType::AddressError
    );
    Ok(addr.into())
  })
}

#[tauri::command]
#[specta::specta]
async fn balance(
  network: String,
  receive: String,
  change: Option<String>,
  electrum: Option<String>,
) -> Result<Balance, TempuraError> {
  let network = Network::from_str(&network)?;
  let blockchain = get_blockchain(network, electrum)?;
  let wallet = get_wallet(network, receive, change)?;

  // Execute blocking wallet sync and balance retrieval in a separate thread context.
  tokio::task::block_in_place(|| {
    resolve!(
      wallet.sync(&blockchain, SyncOptions::default()),
      TempuraErrorType::WalletSyncError
    );

    let balance: bdk::Balance = resolve!(wallet.get_balance(), TempuraErrorType::BalanceError);

    Ok(balance.into())
  })
}

#[tauri::command]
#[specta::specta]
async fn broadcast(
  psbt: String,
  network: String,
  receive: String,
  change: Option<String>,
  electrum: Option<String>,
) -> Result<(), TempuraError> {
  let network = Network::from_str(&network)?;
  let blockchain = get_blockchain(network, electrum)?;
  let wallet = get_wallet(network, receive, change)?;

  let mut psbt = resolve!(
    bdk::bitcoin::psbt::PartiallySignedTransaction::from_str(&psbt),
    TempuraErrorType::PsbtError
  );

  if !resolve!(
    wallet.finalize_psbt(&mut psbt, bdk::SignOptions::default()),
    TempuraErrorType::PsbtError
  ) {
    return Err(TempuraError::new(
      TempuraErrorType::PsbtError,
      "Failed to finalize PSBT",
    ));
  }

  let tx = psbt.extract_tx();
  Ok(resolve!(
    bdk::blockchain::Blockchain::broadcast(&blockchain, &tx),
    TempuraErrorType::TransactionError
  ))
}

#[tauri::command]
#[specta::specta]
async fn estimate_fee(network: String, electrum: Option<String>) -> Result<f32, TempuraError> {
  let network = Network::from_str(&network)?;
  let blockchain = get_blockchain(network, electrum)?;
  Ok(resolve!(
    bdk::blockchain::Blockchain::estimate_fee(&blockchain, 1).map(|f| f.as_sat_per_vb()),
    TempuraErrorType::BlockchainError
  ))
}

/**
 * this function attempts to locate the hwi executable in the PATH or expected directories
 * TODO: move me to the utility section
 */
fn find_hwi() -> Result<String, TempuraError> {
  let path_var = std::env::var("PATH").map_err(|_| {
    TempuraError::new(
      TempuraErrorType::CommandError,
      "Failed to get PATH environment variable",
    )
  })?;

  // split PATH into directories, add the binary directory and the cargo target directory to the front
  // the binary directory will be searched first, and will usually work with local builds and installed packages/msi.
  //   NOTE: this is better than searching the current_dir, as MSI-installed binaries consider the MSI's build directory as the current_dir at runtime.
  // the target directory is where tauri places the hwi executable when building, and will work for local builds (even custom).
  let mut paths: Vec<&str> = path_var
    .split(if cfg!(windows) { ';' } else { ':' })
    .collect();
  let target_path = std::env::var("CARGO_TARGET_DIR").unwrap_or_else(|_| {
    let build_type = {
      #[cfg(debug_assertions)]
      {
        "debug"
      }
      #[cfg(not(debug_assertions))]
      {
        "release"
      }
    };

    #[cfg(target_os = "windows")]
    {
      format!(".\\target\\{}", build_type)
    }

    #[cfg(not(target_os = "windows"))]
    {
      format!("./target/{}", build_type)
    }
  });
  paths.insert(0, &target_path);

  let mut exe_parent_path: String = String::from(".");
  if let Ok(exe_path) = std::env::current_exe() {
    if let Some(parent_dir) = exe_path.parent() {
      exe_parent_path = parent_dir.to_string_lossy().into_owned();
    }
  }
  paths.insert(0, &exe_parent_path);

  // search each directory for the executable
  let hwi_name = if cfg!(windows) { "hwi.exe" } else { "hwi" };
  let hwi_path = paths
    .iter()
    .map(|dir| std::path::Path::new(dir).join(hwi_name))
    .find(|path| {
      path.exists()
        && std::fs::metadata(path)
          .map(|meta| meta.is_file())
          .unwrap_or(false)
    })
    .ok_or_else(|| {
      TempuraError::new(
        TempuraErrorType::CommandError,
        "hwi executable not found in PATH",
      )
    })?;

  Ok(hwi_path.to_string_lossy().into_owned())
}

#[tauri::command]
#[specta::specta]
async fn enumerate(network: String) -> Result<String, TempuraError> {
  let network = Network::from_str(&network)?;
  let network: HwiNetwork = network.into();
  let mut command = get_hwi()?;

  let output = resolve!(
    command
      .args(["--chain", network.as_str(), "enumerate"])
      .output(),
    TempuraErrorType::CommandError
  );

  let output = resolve!(
    String::from_utf8(output.stdout),
    TempuraErrorType::ParseError
  );

  Ok(output)
}

#[tauri::command]
#[specta::specta]
async fn sign(psbt: String, network: String) -> Result<String, TempuraError> {
  let network = Network::from_str(&network)?;
  let network: HwiNetwork = network.into();
  let mut command = get_hwi()?;

  let output = resolve!(
    command
      .args([
        "--chain",
        network.as_str(),
        "--device-type",
        "jade", // TODO: assume jade for now
        "signtx",
        &psbt
      ])
      .output(),
    TempuraErrorType::CommandError
  );

  let output = resolve!(
    String::from_utf8(output.stdout),
    TempuraErrorType::ParseError
  );

  Ok(output)
}

#[tauri::command]
#[specta::specta]
async fn sweep(
  address: String,
  fee_rate: f32,
  network: String,
  receive: String,
  change: Option<String>,
  electrum: Option<String>,
) -> Result<PsbtDetails, TempuraError> {
  let network = Network::from_str(&network)?;
  let blockchain = get_blockchain(network, electrum)?;
  let wallet = get_wallet(network, receive, change)?;

  // Execute blocking wallet sync and balance retrieval in a separate thread context.
  tokio::task::block_in_place(|| {
    resolve!(
      wallet.sync(&blockchain, SyncOptions::default()),
      TempuraErrorType::WalletSyncError
    );

    let mut builder = wallet.build_tx();
    let addr = resolve!(
      bdk::bitcoin::Address::from_str(&address),
      TempuraErrorType::AddressError
    );
    // check that recipient is on the same network as the wallet
    if addr.network != wallet.network() {
      return Err(TempuraError::new(
        TempuraErrorType::AddressError,
        &format!(
          "Mismatched address and network. address: {}, network: {}",
          address, network
        ),
      ));
    }
    builder.drain_wallet();
    builder.drain_to(addr.payload.script_pubkey());
    builder.enable_rbf();
    builder.fee_rate(bdk::FeeRate::from_sat_per_vb(fee_rate));

    let (psbt, details) = resolve!(builder.finish(), TempuraErrorType::TransactionError);
    Ok(PsbtDetails::new(psbt.to_string(), details))
  })
}

/**
 * entrypoint
 */

fn main() {
  let specta_builder: tauri_specta::Builder =
    tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
      address,
      balance,
      estimate_fee,
      broadcast,
      enumerate,
      sign,
      sweep
    ]);

  // disable Specta wrapping Results into javascript objects with {status : 'ok' | 'error'}
  let specta_builder = specta_builder.error_handling(tauri_specta::ErrorHandlingMode::Throw);

  #[cfg(debug_assertions)] // <- Only export on non-release builds
  specta_builder
    .export(Typescript::default(), "../src/bindings.ts")
    .expect("Failed to export typescript bindings");

  tauri::Builder::default()
    .plugin(tauri_plugin_clipboard_manager::init())
    .plugin(tauri_plugin_shell::init())
    .invoke_handler(specta_builder.invoke_handler())
    .setup(move |app| {
      specta_builder.mount_events(app);
      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
