// prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::collections::BTreeMap;
#[cfg(target_os = "windows")]
use std::os::windows::process::CommandExt;

use std::process::Command;
use std::str::FromStr;
use std::sync::Arc;

#[macro_use]
mod errors;
use bdk_wallet::psbt::PsbtUtils;
use errors::{DescriptorType, TempuraError, TempuraErrorType};
mod network;
use network::{HwiNetwork, Network};

// tauri and other framework imports
use serde::{Deserialize, Serialize};
use specta::Type;
use tauri::Manager;

// bdk and bitcoin imports
use bdk_electrum::electrum_client::Client;
use bdk_electrum::BdkElectrumClient;
use bdk_wallet;
use bdk_wallet::bitcoin::secp256k1::Secp256k1;
use bdk_wallet::bitcoin::Amount;
use bdk_wallet::bitcoin::Psbt;
use bdk_wallet::descriptor::IntoWalletDescriptor;
use bitcoin_units::fee_rate::FeeRate;

const DEFAULT_STOP_GAP: usize = 100;
const DEFAULT_BATCH_SIZE: usize = 10;

/**
 * types
 */

#[derive(Default, Serialize, Deserialize, Type)]
pub struct AddressInfo {
  pub index: u32,
  pub address: String,
}

impl From<bdk_wallet::AddressInfo> for AddressInfo {
  fn from(addrinfo: bdk_wallet::AddressInfo) -> Self {
    Self {
      index: addrinfo.index,
      address: addrinfo.address.to_string(),
    }
  }
}

// this type is copied from BDK so that we can specta-derive it,
// but unfortunately u64 is not supported, so we must convert to string.
#[derive(Default, Serialize, Deserialize, Type)]
pub struct Balance {
  /// All coinbase outputs not yet matured
  pub immature: String,
  /// Unconfirmed UTXOs generated by a wallet tx
  pub trusted_pending: String,
  /// Unconfirmed UTXOs received from an external wallet
  pub untrusted_pending: String,
  /// Confirmed and immediately spendable balance
  pub confirmed: String,
}

impl From<bdk_wallet::Balance> for Balance {
  fn from(balance: bdk_wallet::Balance) -> Self {
    Balance {
      immature: balance.immature.to_string(),
      trusted_pending: balance.trusted_pending.to_string(),
      untrusted_pending: balance.untrusted_pending.to_string(),
      confirmed: balance.confirmed.to_string(),
    }
  }
}

#[derive(Default, Serialize, Deserialize, Type)]
struct Descriptors {
  pub receive: String,
  pub change: Option<String>,
  pub auto_change: bool,
}

impl Descriptors {
  pub fn new(receive: String, change: Option<String>, auto_change: bool) -> Self {
    Descriptors {
      receive: receive,
      change: change,
      auto_change: auto_change,
    }
  }
}

// again, unfortunately u64 is not supported, so we must convert to string for number values.
#[derive(Default, Serialize, Deserialize, Type)]
pub struct PsbtDetails {
  pub psbt: String,
  pub txid: String,
  pub received: String,
  pub sent: String,
  pub fee: Option<String>,
  pub outbound: String,
}

impl PsbtDetails {
  pub fn new(psbt: Psbt) -> Self {
    let tx = psbt.clone().extract_tx().unwrap();
    let fee = psbt
      .fee_amount()
      // .or(Some(Amount::ZERO))
      .map(|f| f.to_string());

    // TODO VUP: double check denominations returned against OG.
    // This Amount class supports converting to string in different demoninations
    // https://docs.rs/bitcoin/0.32.5/bitcoin/struct.Amount.html#method.to_string_in
    let sent = tx.output.iter().map(|o| o.value).sum::<Amount>();

    // I'm gonna have to pass the wallet into this function to determine manually which outputs are mine
    // to determine the sent and received amounts.

    PsbtDetails {
      psbt: psbt.to_string(),
      txid: tx.compute_txid().to_string(),
      received: "".to_string(), // TODO VUP: details.received.to_string(),
      sent: sent.to_string(),
      fee,
      outbound: "".to_string(), // TODO VUP: outbound.to_string(),
    }
  }
}

#[derive(Debug, Serialize, Deserialize, Type)]
enum PsbtSigningStatus {
  Unsigned,
  PartiallySigned,
  FullySigned,
}

#[derive(Default, Serialize, Deserialize, Type)]
pub struct TxIn {
  pub txid: String,
  pub vout: u32,
}

impl From<&bdk_wallet::bitcoin::blockdata::transaction::TxIn> for TxIn {
  fn from(i: &bdk_wallet::bitcoin::blockdata::transaction::TxIn) -> Self {
    TxIn {
      txid: i.previous_output.txid.to_string(),
      vout: i.previous_output.vout,
    }
  }
}

#[derive(Default, Serialize, Deserialize, Type)]
pub struct TxOut {
  pub address: Option<String>,
  pub script: String,
  pub amount: String,
}

impl From<&bdk_wallet::bitcoin::blockdata::transaction::TxOut> for TxOut {
  fn from(o: &bdk_wallet::bitcoin::blockdata::transaction::TxOut) -> Self {
    TxOut {
      address: None,
      script: o.script_pubkey.to_asm_string(),
      amount: o.value.to_string(),
    }
  }
}

#[derive(Default, Serialize, Deserialize, Type)]
pub struct Transaction {
  pub version: i32,
  pub locktime: u32,
  pub ins: Vec<TxIn>,
  pub outs: Vec<TxOut>,
  pub txid: String,
  pub received: String,
  pub sent: String,
  pub fee: String,
  pub confirmation_height: Option<u32>,
}

// TODO VUP
// impl TryFrom<&bdk_wallet::chain::tx_graph::CanonicalTx<'_, std::sync::Arc<bdk_wallet::bitcoin::Transaction>, bdk_wallet::chain::ConfirmationBlockTime>> for Transaction {
//   impl<'a> TryFrom<&'a bdk_wallet::WalletTx<'a>> for Transaction {
//   type Error = &'static str;

//   fn try_from(tx: &bdk_wallet::chain::tx_graph::CanonicalTx<'_, std::sync::Arc<bdk_wallet::bitcoin::Transaction>, bdk_wallet::chain::ConfirmationBlockTime>) -> Result<Self, Self::Error> {

//     let t = Transaction {
//       version: tx.tx_node.version.into() as i32, // TODO VUP: verify the version conversion
//       locktime: tx.tx_node.lock_time.to_consensus_u32(),
//       ins: (&tx.tx_node.input).into_iter().map(|i| i.into()).collect(),
//       outs: (&tx.tx_node.output).into_iter().map(|o| o.into()).collect(),
//       txid: tx.tx_node.txid.to_string(),
//       received: tx.received.to_string(),
//       sent: tx.sent.to_string(),
//       fee: tx.fee.unwrap().to_string(),
//       confirmation_height: tx.chain_position.confirmation_time.clone().map(|ct| ct.height),
//     }

//     match &td.transaction {
//       None => Err("Required raw transaction data not present"),
//       Some(tx) => Ok(Transaction {
//         version: tx.version.into(),
//         locktime: tx.lock_time.to_consensus_u32(),
//         ins: (&tx.input).into_iter().map(|i| i.into()).collect(),
//         outs: (&tx.output).into_iter().map(|o| o.into()).collect(),
//         txid: td.txid.to_string(),
//         received: td.received.to_string(),
//         sent: td.sent.to_string(),
//         fee: td.fee.unwrap().to_string(),
//         confirmation_height: td.confirmation_time.clone().map(|ct| ct.height),
//       }),
//     }
//   }
// }

#[derive(Default, Serialize, Deserialize, Type)]
pub struct Wallet {
  pub balance: Balance,
  pub transactions: Vec<Transaction>,
}

/**
 * utilities
 */

fn get_blockchain(
  network: Network,
  electrum: Option<String>,
) -> Result<BdkElectrumClient<Client>, TempuraError> {
  let connection = match electrum {
    Some(electrum) => electrum,
    None => match network {
      Network::Testnet => "ssl://electrum.blockstream.info:60002".to_string(),
      Network::Bitcoin => "ssl://blockstream.info:993".to_string(),
      Network::Regtest => "localhost:50021".to_string(),
      _ => {
        return Err(TempuraError::new(
          TempuraErrorType::NetworkError,
          "You must specify an electrum server for this network",
        ))
      }
    },
  };

  let client = resolve!(Client::new(&connection), TempuraErrorType::ClientError);
  Ok(BdkElectrumClient::new(client))
}

fn get_hwi() -> Result<Command, TempuraError> {
  let hwi_path = hwi_path();

  #[allow(unused_mut)]
  let mut command = Command::new(&hwi_path);
  #[cfg(target_os = "windows")]
  {
    const COMMAND_FLAG_CREATE_NO_WINDOW: u32 = 0x08000000;
    command.creation_flags(COMMAND_FLAG_CREATE_NO_WINDOW);
  }
  Ok(command)
}

fn get_wallet(
  network: Network,
  descriptors: Descriptors,
) -> Result<bdk_wallet::Wallet, TempuraError> {
  let secp = Secp256k1::new();
  let network: bdk_wallet::bitcoin::Network = network.into();

  type DescriptorTupleType = (
    bdk_wallet::miniscript::Descriptor<bdk_wallet::keys::DescriptorPublicKey>,
    BTreeMap<bdk_wallet::keys::DescriptorPublicKey, bdk_wallet::keys::DescriptorSecretKey>,
  );
  let receive: DescriptorTupleType;
  let mut change: Option<DescriptorTupleType> = None;

  if let Some(change_descriptor) = &descriptors.change {
    if is_multipath_descriptor(&descriptors.receive) {
      return Err(TempuraError::new(
        TempuraErrorType::DescriptorError(Some(DescriptorType::Receive)),
        "A change descriptor must not be provided when using multipath descriptors",
      ));
    }

    if is_multipath_descriptor(change_descriptor) {
      return Err(TempuraError::new(
      TempuraErrorType::DescriptorError(Some(DescriptorType::Change)),
      "A change descriptor must not be a multipath descriptor. Use this as a receive descriptor instead.",
    ));
    }
  }

  // we must handle multipath descriptors first to avoid BDK exceptions. see `split_descriptor_if_multipath`.
  if let Some((receive_descriptor, change_descriptor)) =
    split_descriptor_if_multipath(&descriptors.receive)?
  {
    receive = resolve!(
      receive_descriptor.into_wallet_descriptor(&secp, network),
      TempuraErrorType::DescriptorError(Some(DescriptorType::Multipath))
    );

    change = Some(resolve!(
      change_descriptor.into_wallet_descriptor(&secp, network),
      TempuraErrorType::DescriptorError(Some(DescriptorType::Multipath))
    ));
  } else {
    receive = resolve!(
      descriptors.receive.into_wallet_descriptor(&secp, network),
      TempuraErrorType::DescriptorError(Some(DescriptorType::Receive))
    );
  }

  // Convert a provided change descriptor
  if let Some(change_descriptor) = &descriptors.change {
    change = Some(resolve!(
      change_descriptor.into_wallet_descriptor(&secp, network),
      TempuraErrorType::DescriptorError(Some(DescriptorType::Change))
    ));
  }

  // handle auto change calculation if not already set
  if change.is_none() && receive.0.has_wildcard() && descriptors.auto_change {
    let receive_str = receive.0.to_string();
    let change_str = receive_str.replace("/0/*", "/1/*");
    let change_str = match change_str.rfind("#") {
      Some(i) => {
        let (change_str, _) = change_str.split_at(i);
        change_str.to_string()
      }
      None => change_str,
    };
    change = match change_str == receive_str {
      true => None,
      false => Some(resolve!(
        change_str.into_wallet_descriptor(&secp, network),
        TempuraErrorType::DescriptorError(Some(DescriptorType::Change))
      )),
    }
  };

  let wallet_result = if let Some(change) = change {
    bdk_wallet::Wallet::create(receive, change)
  } else {
    bdk_wallet::Wallet::create_single(receive)
  }
  .network(network)
  .create_wallet_no_persist();

  Ok(resolve!(wallet_result, TempuraErrorType::WalletError))
}

fn is_multipath_descriptor(descriptor: &str) -> bool {
  bdk_wallet::descriptor::ExtendedDescriptor::from_str(descriptor)
    .map(|d| d.is_multipath())
    .unwrap_or(false)
}

/**
 * we only pseudo-support multipath descriptors, as BDK does not currently support them.
 * this function will split a multipath descriptor into two single path descriptors.
 */
fn split_descriptor_if_multipath(
  descriptor: &str,
) -> Result<Option<(String, String)>, TempuraError> {
  // we use `from_str` instead of `into_wallet_descriptor` intentionally, the former
  // does not consider the network when converting. BDK throws exceptions if you try to use
  // use the latter with a multipath descriptor on mainnet. yet, we should rely on BDK to
  // perform the conversion rather than parsing the strings manually.
  let receive = match bdk_wallet::descriptor::ExtendedDescriptor::from_str(&descriptor) {
    Ok(result) => result,
    Err(_) => return Ok(None),
  };

  if !receive.is_multipath() {
    return Ok(None);
  }

  let paths = resolve!(
    receive.clone().into_single_descriptors(),
    TempuraErrorType::DescriptorError(Some(DescriptorType::Multipath))
  );

  if paths.len() != 2 {
    return Err(TempuraError::new(
      TempuraErrorType::DescriptorError(Some(DescriptorType::Multipath)),
      "A multipath descriptor must have exactly two paths",
    ));
  }

  let receive = paths[0].clone().to_string();
  let change = paths[1].clone().to_string();

  Ok(Some((receive, change)))
}

/**
 * some expected locations for the hwi executable will not be found when searching the system PATH.
 *
 * this function will attempt to find the hwi executable in the following locations, by priority:
 *   - the TEMPURA_HWI_PATH environment variable, if specified
 *   - the directory where the binary is running from, or current directory
 *   - the CARGO_TARGET_DIR environment variable, if specified
 */
fn hwi_path() -> String {
  let mut paths: Vec<String> = Vec::new();
  if let Ok(path) = std::env::var("CARGO_TARGET_DIR") {
    paths.push(path);
  }

  let mut exe_parent_path: String = String::from(".");
  if let Ok(exe_path) = std::env::current_exe() {
    if let Some(parent_dir) = exe_path.parent() {
      exe_parent_path = parent_dir.to_string_lossy().into_owned();
    }
  }
  paths.insert(0, exe_parent_path);

  if let Ok(path) = std::env::var("TEMPURA_HWI_PATH") {
    paths.insert(0, path);
  }

  // search each directory for the executable
  let hwi_name = if cfg!(windows) { "hwi.exe" } else { "hwi" };
  let hwi_path = paths
    .iter()
    .map(|dir| std::path::Path::new(dir).join(hwi_name))
    .find(|path| {
      path.exists()
        && std::fs::metadata(path)
          .map(|meta| meta.is_file())
          .unwrap_or(false)
    });

  if let Some(hwi_path) = hwi_path {
    return hwi_path.to_string_lossy().into_owned();
  }

  // let the system try to find it in PATH, '.exe' not necessary.
  String::from("hwi")
}

fn sync_wallet(
  wallet: &mut bdk_wallet::Wallet,
  blockchain: &BdkElectrumClient<Client>,
) -> Result<(), TempuraError> {
  let request = wallet.start_full_scan();
  let update = resolve!(
    blockchain.full_scan(request, DEFAULT_STOP_GAP, DEFAULT_BATCH_SIZE, false),
    TempuraErrorType::WalletSyncError
  );
  resolve!(
    wallet.apply_update(update),
    TempuraErrorType::WalletSyncError
  );
  Ok(())
}

/**
 * interface functions
 */

#[tauri::command]
#[specta::specta]
async fn address(
  network: String,
  descriptors: Descriptors,
  electrum: Option<String>,
) -> Result<AddressInfo, TempuraError> {
  let network = Network::from_str(&network)?;
  let blockchain = get_blockchain(network, electrum)?;
  let mut wallet = get_wallet(network, descriptors)?;

  // Execute blocking wallet sync in a separate thread context.
  tokio::task::block_in_place(|| {
    sync_wallet(&mut wallet, &blockchain)?;

    let addr = wallet.next_unused_address(bdk_wallet::KeychainKind::External);
    Ok(addr.into())
  })
}

#[tauri::command]
#[specta::specta]
async fn broadcast(
  psbt: String,
  network: String,
  descriptors: Descriptors,
  electrum: Option<String>,
) -> Result<(), TempuraError> {
  let network = Network::from_str(&network)?;
  let blockchain = get_blockchain(network, electrum)?;
  let wallet = get_wallet(network, descriptors)?;

  let mut psbt = resolve!(
    bdk_wallet::bitcoin::psbt::Psbt::from_str(&psbt),
    TempuraErrorType::PsbtError
  );

  if !resolve!(
    wallet.finalize_psbt(&mut psbt, bdk_wallet::SignOptions::default()),
    TempuraErrorType::PsbtError
  ) {
    return Err(TempuraError::new(
      TempuraErrorType::PsbtError,
      "Failed to finalize the PSBT for broadcast, it may be missing required signatures.",
    ));
  }

  let tx = resolve!(psbt.extract_tx(), TempuraErrorType::PsbtError);
  let _txid = resolve!(
    blockchain.transaction_broadcast(&tx),
    TempuraErrorType::TransactionError
  );
  Ok(())
}

#[tauri::command]
#[specta::specta]
async fn estimate_fee(
  network: String,
  electrum: Option<String>,
  blocks: Option<u32>,
) -> Result<f64, TempuraError> {
  let network = Network::from_str(&network)?;
  let blockchain = get_blockchain(network, electrum)?;
  let blocks = blocks.unwrap_or(1) as usize;

  // BDK may panic here when the electrum server returns a value that it doesn't expect.
  let result = std::panic::catch_unwind(|| {
    bdk_electrum::electrum_client::ElectrumApi::estimate_fee(&blockchain.inner, blocks)
  });

  match result {
    Ok(inner_result) => match inner_result {
      Ok(fee) => Ok(fee),
      Err(e) => Err(TempuraError::new(
        TempuraErrorType::BlockchainError,
        &e.to_string(),
      )),
    },
    Err(_) => Err(TempuraError::new(
      TempuraErrorType::BlockchainError,
      "An unexpected error occurred while estimating the fee",
    )),
  }
}

#[tauri::command]
#[specta::specta]
async fn enumerate(network: String) -> Result<String, TempuraError> {
  let network = Network::from_str(&network)?;
  let network: HwiNetwork = network.into();
  let mut command = get_hwi()?;

  Ok(resolve_io!(command.args([
    "--chain",
    network.as_str(),
    "enumerate"
  ])))
}

#[tauri::command]
#[specta::specta]
async fn is_address(address: String) -> bool {
  bdk_wallet::bitcoin::Address::from_str(&address).is_ok()
}

#[tauri::command]
#[specta::specta]
async fn is_address_for_network(address: String, network: String) -> Result<bool, TempuraError> {
  let network: bdk_wallet::bitcoin::Network = Network::from_str(&network)?.into();

  let addr = resolve!(
    bdk_wallet::bitcoin::Address::from_str(&address),
    TempuraErrorType::AddressError
  );

  Ok(addr.is_valid_for_network(network))
}

#[tauri::command]
#[specta::specta]
async fn is_address_mine(
  address: String,
  network: String,
  descriptors: Descriptors,
) -> Result<bool, TempuraError> {
  let network = Network::from_str(&network)?;
  let mut wallet = get_wallet(network, descriptors)?;
  let network: bdk_wallet::bitcoin::Network = network.into();

  let addr = resolve!(
    bdk_wallet::bitcoin::Address::from_str(&address),
    TempuraErrorType::AddressError
  );

  let addr = addr.require_network(network).map_err(|_| {
    TempuraError::new(
      TempuraErrorType::AddressError,
      &format!(
        "Mismatched address and network. address: {}, network: {}",
        address, network
      ),
    )
  })?;

  // TODO VUP: let's make sure this doesn't cause problems with no change descriptor
  let receive_index = wallet.next_derivation_index(bdk_wallet::KeychainKind::External);
  let _ = wallet.reveal_addresses_to(
    bdk_wallet::KeychainKind::External,
    receive_index + (DEFAULT_STOP_GAP as u32),
  );
  let change_index = wallet.next_derivation_index(bdk_wallet::KeychainKind::Internal);
  let _ = wallet.reveal_addresses_to(
    bdk_wallet::KeychainKind::Internal,
    change_index + (DEFAULT_STOP_GAP as u32),
  );

  Ok(wallet.is_mine(addr.script_pubkey()))
}

#[tauri::command]
#[specta::specta]
async fn is_descriptor(descriptor: String) -> bool {
  bdk_wallet::descriptor::ExtendedDescriptor::from_str(&descriptor).is_ok()
}

#[tauri::command]
#[specta::specta]
async fn is_descriptor_for_network(
  descriptor: String,
  network: String,
) -> Result<bool, TempuraError> {
  let secp = Secp256k1::new();
  let network: bdk_wallet::bitcoin::Network = Network::from_str(&network)?.into();
  let descriptor =
    split_descriptor_if_multipath(&descriptor)?.map_or(descriptor, |(receive, _)| receive);

  match descriptor.into_wallet_descriptor(&secp, network) {
    Ok(_) => Ok(true),
    Err(e) => match e {
      bdk_wallet::descriptor::DescriptorError::Key(bdk_wallet::keys::KeyError::InvalidNetwork) => {
        Ok(false)
      }
      _ => Err(TempuraError::new(
        TempuraErrorType::DescriptorError(None),
        &e.to_string(),
      )),
    },
  }
}

#[tauri::command]
#[specta::specta]
async fn is_psbt(psbt: String) -> bool {
  return bdk_wallet::bitcoin::psbt::Psbt::from_str(&psbt).is_ok();
}

#[tauri::command]
#[specta::specta]
async fn psbt_status(
  psbt: String,
  network: String,
  descriptors: Descriptors,
) -> Result<PsbtSigningStatus, TempuraError> {
  let psbt = resolve!(
    bdk_wallet::bitcoin::psbt::Psbt::from_str(&psbt),
    TempuraErrorType::PsbtError
  );
  let network = Network::from_str(&network)?;
  let wallet = get_wallet(network, descriptors)?;

  // suceeds if the PSBT is already finalized or the given wallet is able to finalize it
  match wallet.finalize_psbt(&mut psbt.clone(), bdk_wallet::SignOptions::default()) {
    Ok(true) => {
      return Ok(PsbtSigningStatus::FullySigned);
    }
    _ => {}
  }

  // it is possible that the PSBT's spending conditions are actually satisfied,
  // but the given wallet is unable to finalize it.
  for input in &psbt.inputs {
    if !input.partial_sigs.is_empty()
      || !input.tap_script_sigs.is_empty()
      || input.tap_key_sig.is_some()
    {
      return Ok(PsbtSigningStatus::PartiallySigned);
    }
  }

  Ok(PsbtSigningStatus::Unsigned)
}

#[tauri::command]
#[specta::specta]
async fn sign(psbt: String, network: String, device_type: String) -> Result<String, TempuraError> {
  let network = Network::from_str(&network)?;
  let network: HwiNetwork = network.into();
  let mut command = get_hwi()?;

  Ok(resolve_io!(command.args([
    "--chain",
    network.as_str(),
    "--device-type",
    &device_type,
    "signtx",
    &psbt
  ])))
}

#[tauri::command]
#[specta::specta]
async fn sweep(
  address: String,
  fee_rate: f32,
  network: String,
  descriptors: Descriptors,
  electrum: Option<String>,
) -> Result<PsbtDetails, TempuraError> {
  let network = Network::from_str(&network)?;
  let blockchain = get_blockchain(network, electrum)?;
  let mut wallet = get_wallet(network, descriptors)?;
  let wallet_network = wallet.network();

  // TODO VUP: can we convert the interface to accept a u64 instead of f32?
  if fee_rate < 0.0 {
    return Err(TempuraError::new(
      TempuraErrorType::FeeRateError,
      "Fee rate must be a positive number",
    ));
  }
  let fee_rate: u64 = fee_rate.ceil() as u64;
  let fee_rate = FeeRate::from_sat_per_vb(fee_rate).ok_or(TempuraError::new(
    TempuraErrorType::FeeRateError,
    "Invalid fee rate",
  ))?;

  // Execute blocking wallet sync and balance retrieval in a separate thread context.
  tokio::task::block_in_place(|| {
    sync_wallet(&mut wallet, &blockchain)?;

    let mut builder = wallet.build_tx();
    let addr = resolve!(
      bdk_wallet::bitcoin::Address::from_str(&address),
      TempuraErrorType::AddressError
    );

    let addr = addr.require_network(wallet_network).map_err(|_| {
      TempuraError::new(
        TempuraErrorType::AddressError,
        &format!(
          "Mismatched address and network. address: {}, network: {}",
          address, network
        ),
      )
    })?;

    builder.drain_wallet();
    builder.drain_to(addr.script_pubkey());
    builder.fee_rate(fee_rate);

    let psbt = resolve!(builder.finish(), TempuraErrorType::TransactionError);
    Ok(PsbtDetails::new(psbt))
  })
}

#[tauri::command]
#[specta::specta]
async fn wallet(
  network: String,
  descriptors: Descriptors,
  electrum: Option<String>,
) -> Result<Wallet, TempuraError> {
  let network = Network::from_str(&network)?;
  let blockchain = get_blockchain(network, electrum)?;
  let mut wallet = get_wallet(network, descriptors)?;

  // Execute blocking wallet sync and balance retrieval in a separate thread context.
  tokio::task::block_in_place(|| {
    sync_wallet(&mut wallet, &blockchain)?;

    // let t = wallet.transactions().;
    let txs = wallet.transactions();
    let transactions_result: Result<Vec<Transaction>, TempuraError> = txs
      .into_iter()
      .map(|mut tx| {
        let tx2: bdk_wallet::bitcoin::Transaction = Arc::make_mut(&mut tx.tx_node.tx).clone();
        let (sent, received) = wallet.sent_and_received(&tx2);
        let fee = resolve!(
          wallet.calculate_fee(&tx2),
          TempuraErrorType::TransactionError
        );
        let t = Transaction {
          version: tx.tx_node.version.0, // TODO VUP: verify the version conversion
          locktime: tx.tx_node.lock_time.to_consensus_u32(),
          ins: (&tx.tx_node.input).into_iter().map(|i| i.into()).collect(),
          outs: (&tx.tx_node.output).into_iter().map(|o| o.into()).collect(),
          txid: tx.tx_node.txid.to_string(),
          received: received.to_string(),
          sent: sent.to_string(),
          fee: fee.to_string(),
          confirmation_height: tx.chain_position.confirmation_height_upper_bound().clone(),
        };

        //     let mut t = resolve!(
        //       TryInto::<Transaction>::try_into(&td),
        //       TempuraErrorType::TransactionsError
        //     );

        //     // Populating addresses requires the network, so can't be done in the main `try_into`
        //     let bdk_tx = resolve!(
        //       td.transaction.ok_or("Missing required raw transaction"),
        //       TempuraErrorType::TransactionsError
        //     );
        //     (&mut t.outs).into_iter().enumerate().for_each(|(x, o)| {
        //       let script = bdk_tx.output[x].script_pubkey.as_script();
        //       o.address = bdk::bitcoin::Address::from_script(script, network.into())
        //         .ok()
        //         .map(|a| a.to_string());
        //     });
        Ok(t)
      })
      .collect();
    let balance: Balance = wallet.balance().into();
    transactions_result.map(|transactions| Wallet {
      balance,
      transactions,
    })
  })
}

#[tauri::command]
#[specta::specta]
async fn create_window(
  app: tauri::AppHandle,
  label: String,
  html: String,
  title: String,
  width: f64,
  height: f64,
) {
  // First check if a window with the label already exists and if so, show it
  if let Some(window) = app.get_webview_window(&label) {
    window.show().unwrap();
  } else {
    // Otherwise, create a new window
    let _webview_window =
      tauri::WebviewWindowBuilder::new(&app, label, tauri::WebviewUrl::App(html.into()))
        .title(title)
        .inner_size(width, height)
        .build()
        .unwrap();
  }
}

/**
 * entrypoint
 */

fn main() {
  let specta_builder: tauri_specta::Builder =
    tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
      address,
      broadcast,
      enumerate,
      estimate_fee,
      is_address,
      is_address_for_network,
      is_address_mine,
      is_descriptor,
      is_descriptor_for_network,
      is_psbt,
      psbt_status,
      sign,
      sweep,
      wallet,
      create_window
    ]);

  // disable Specta wrapping Results into javascript objects with {status : 'ok' | 'error'}
  let specta_builder = specta_builder.error_handling(tauri_specta::ErrorHandlingMode::Throw);

  #[cfg(debug_assertions)]
  specta_builder
    .export(
      specta_typescript::Typescript::default(),
      "../src/bindings.ts",
    )
    .expect("Failed to export typescript bindings");

  tauri::Builder::default()
    .plugin(tauri_plugin_clipboard_manager::init())
    .plugin(tauri_plugin_shell::init())
    .invoke_handler(specta_builder.invoke_handler())
    .setup(move |app| {
      specta_builder.mount_events(app);
      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
