
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async address(network: string, descriptor: string, electrum: string | null) : Promise<AddressInfo> {
    return await TAURI_INVOKE("address", { network, descriptor, electrum });
},
async balance(network: string, receive: string, change: string | null, electrum: string | null) : Promise<Balance> {
    return await TAURI_INVOKE("balance", { network, receive, change, electrum });
},
async broadcast(psbt: string, network: string, receive: string, change: string | null, electrum: string | null) : Promise<null> {
    return await TAURI_INVOKE("broadcast", { psbt, network, receive, change, electrum });
},
async sign(message: string, network: string) : Promise<number[]> {
    return await TAURI_INVOKE("sign", { message, network });
},
async sweep(address: string, feeRate: number, network: string, receive: string, change: string | null, electrum: string | null) : Promise<PsbtDetails> {
    return await TAURI_INVOKE("sweep", { address, feeRate, network, receive, change, electrum });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AddressInfo = { index: number; address: string }
export type Balance = { 
/**
 * All coinbase outputs not yet matured
 */
immature: string; 
/**
 * Unconfirmed UTXOs generated by a wallet tx
 */
trusted_pending: string; 
/**
 * Unconfirmed UTXOs received from an external wallet
 */
untrusted_pending: string; 
/**
 * Confirmed and immediately spendable balance
 */
confirmed: string }
export type PsbtDetails = { psbt: string; txid: string; received: string; sent: string; fee: string | null }
export type TempuraError = { error_type: string; message: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
