name: Build Swan Vault Recovery Assistant release

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # https://github.com/actions/runner-images
        os: [ubuntu-latest, windows-latest, macos-latest]
        isPR:
          - ${{github.event_name == 'pull_request'}}
        allBundles:
          - ${{contains(github.event.pull_request.labels.*.name, 'all bundles')}}
        exclude:
          - isPR: true
            allBundles: false
            os: ubuntu-latest
          - isPR: true
            allBundles: false
            os: windows-latest

    steps:
      - name: Checkout code
        uses: swan-bitcoin/actions/actions/checkout@master

      - name: Set up Rust
        uses: swan-bitcoin/actions/actions-rs/toolchain@master
        with:
          toolchain: stable
          override: true

      - uses: swan-bitcoin/actions/pnpm/action-setup@master
        with:
          version: 9
      - uses: swan-bitcoin/actions/actions/setup-node@master
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install system dependencies (linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get install -y build-essential curl wget file libwebkit2gtk-4.1-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore cargo cache
        id: restore-cargo-cache
        uses: swan-bitcoin/actions/actions/cache/restore@master
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
            !src-tauri/target/release/hwi
            !src-tauri/target/release/hwi.exe
            !src-tauri/target/release/swan-vault-recovery-assistant
            !src-tauri/target/release/swan-vault-recovery-assistant.exe
            !src-tauri/target/release/bundle
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '.github/workflows/build.yml') }}

      - name: Import Apple Developer Certificate
        if: ${{ matrix.os == 'macos-latest' && !matrix.isPR }}
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          security find-identity -v -p codesigning build.keychain

      - name: Verify Apple Developer Certificate
        if: ${{ matrix.os == 'macos-latest' && !matrix.isPR }}
        run: |
          CERT_INFO=$(security find-identity -v -p codesigning build.keychain | grep "Developer ID Application")
          CERT_ID=$(echo "$CERT_INFO" | awk -F'"' '{print $2}')
          echo "APPLE_SIGNING_IDENTITY=$CERT_ID" >> $GITHUB_ENV
          echo "Apple Developer Certificate imported."

      - name: Save Apple API Key
        if: ${{ matrix.os == 'macos-latest' && !matrix.isPR }}
        env:
          APPLE_API_KEY_B64: ${{ secrets.APPLE_API_KEY_B64 }}
        run: |
          APPLE_API_KEY_PATH=$HOME/apple_api.key
          echo ${APPLE_API_KEY_B64} | base64 -d > $APPLE_API_KEY_PATH
          echo "APPLE_API_KEY_PATH=$APPLE_API_KEY_PATH" >> $GITHUB_ENV
          echo "Apple API Key saved."

      - name: Build project (signed Mac app)
        if: ${{ matrix.os == 'macos-latest' && !matrix.isPR }}
        env:
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
        run: pnpm tauri build

      - name: Build project (unsigned)
        if: ${{ matrix.os != 'macos-latest' || matrix.isPR }}
        run: pnpm tauri build

      - name: Check for git diffs after build
        run: pnpm ci:gitdiff

      - name: Save cargo cache
        uses: swan-bitcoin/actions/actions/cache/save@master
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
            !src-tauri/target/release/hwi
            !src-tauri/target/release/hwi.exe
            !src-tauri/target/release/swan_vault_recovery_assistant
            !src-tauri/target/release/swan_vault_recovery_assistant.exe
            !src-tauri/target/release/bundle
          key: ${{ steps.restore-cargo-cache.outputs.cache-primary-key }}

        # https://jonaskruckenberg.github.io/tauri-docs-wip/building/building-your-application.html#packaging-formats
      - name: Publish artifacts (linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: swan-bitcoin/actions/actions/upload-artifact@master
        with:
          name: swan-vault-recovery-assistant-linux
          path: |
            src-tauri/target/release/bundle/deb/Swan*.deb
            src-tauri/target/release/bundle/appimage/Swan*.AppImage
            src-tauri/target/release/bundle/rpm/Swan*.rpm

      - name: Publish artifacts (macos)
        if: ${{ matrix.os == 'macos-latest' }}
        uses: swan-bitcoin/actions/actions/upload-artifact@master
        with:
          name: swan-vault-recovery-assistant-macos
          path: |
            src-tauri/target/release/bundle/macos/Swan*.app
            src-tauri/target/release/bundle/dmg/Swan*.dmg

      - name: Publish artifacts (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: swan-bitcoin/actions/actions/upload-artifact@master
        with:
          name: swan-vault-recovery-assistant-windows
          path: |
            src-tauri/target/release/bundle/msi/Swan*.msi
            src-tauri/target/release/bundle/nsis/Swan*.exe
