name: Build tempura release

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # https://github.com/actions/runner-images
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        if: ${{ matrix.os != 'windows-latest' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Node.js
        if: ${{ matrix.os != 'windows-latest' }}
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install system dependencies (linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get install -y build-essential curl wget file libwebkit2gtk-4.1-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      # - name: Install system dependencies (macos)
      #   if: ${{ matrix.os == 'macos-latest' }}
      #   run: brew install gtk+3 webkit2gtk

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm tauri build

        # https://jonaskruckenberg.github.io/tauri-docs-wip/building/building-your-application.html#packaging-formats
      - name: Publish artifacts (linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: tempura-linux
          path: |
            src-tauri/target/release/bundle/deb/tempura*.deb
            src-tauri/target/release/bundle/appimage/tempura*.AppImage
            src-tauri/target/release/bundle/rpm/tempura*.rpm

      - name: Publish artifacts (macos)
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: tempura-macos
          path: |
            src-tauri/target/release/bundle/macos/tempura.app
            src-tauri/target/release/bundle/dmg/tempura*.dmg

      - name: Publish artifacts (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: tempura-windows
          path: |
            src-tauri/target/release/bundle/msi/tempura*.msi
            src-tauri/target/release/bundle/nsis/tempura*.exe
